name: HACS

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  validate:
    name: Validate with HACS
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Validate integration
        if: ${{ hashFiles('custom_components/*/manifest.json') != '' }}
        uses: hacs/action@main
        with:
          category: integration

